apiVersion: v1
kind: ConfigMap
metadata:
    # config map name, will be used by deployments, cronjobs, etc
    name: configmap
    namespace: default
    annotations:
        source_url: "git@gitlab.com:kisphp/example.git"
#immutable: true
data:
    APP_ENV: prod

    MYSQL_HOST: "127.0.0.1"
    MYSQL_USER: mysql_username_here

    UPLOAD_DIRECTORY: /data/uploads

    # file-like keys
    game.properties: |
        enemy.types=aliens,machines,humans
        player.maximum-lives=5

    user-interface.properties: |
        color.good=purple
        color.bad=yellow
        color.textmode=true
